version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/load-data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5432:5432"
    networks:
      - popup-chinese-network


volumes:
  pg-data-volume:

networks:
  popup-chinese-network:
