version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/load-data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    ports:
      - "8443:8443"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./cert/keycloak-cert.pem:/etc/keycloak-cert.pem
      - ./cert/keycloak-private-key.pem:/etc/keycloak-key.pem
      - ./scripts/keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    command: ['start',
              '--hostname-strict=false',
              '--https-certificate-file=/etc/keycloak-cert.pem',
              '--https-certificate-key-file=/etc/keycloak-key.pem',
              '--log-level=INFO',
              '--import-realm']
    depends_on:
      - "postgres"

  app:
    image: dcnis/popup-chinese-backend-quarkus
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: secret
      DB_URI: jdbc:postgresql://postgres:5432/popupchinese
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - "keycloak"

volumes:
  pg-data-volume:

