CREATE TABLE IF NOT EXISTS lessons (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     title VARCHAR(50) NOT NULL,
     discussion TEXT,
     difficulty VARCHAR(50),
     thumbnail_url VARCHAR(255),
     audio_url VARCHAR(255)
     );

CREATE TABLE IF NOT EXISTS vocabularies (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     lesson_id BIGINT NOT NULL,
     chinese VARCHAR(50),
     pinyin VARCHAR(50),
     english VARCHAR(50),
     category VARCHAR(50),
     vocabulary_order INT
     );

CREATE TABLE IF NOT EXISTS dialogs (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     lesson_id BIGINT NOT NULL,
     chinese VARCHAR(50),
     pinyin VARCHAR(50),
     english VARCHAR(50),
     speaker VARCHAR(50),
     dialog_order INT
     );

