CREATE SEQUENCE IF NOT EXISTS lessons_seq START 1 INCREMENT 1;
CREATE TABLE IF NOT EXISTS lessons (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     title VARCHAR(50) NOT NULL,
     discussion TEXT,
     difficulty VARCHAR(50),
     thumbnail_url VARCHAR(255),
     audio_url VARCHAR(255)
     );

