CREATE TABLE IF NOT EXISTS lessons (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     title VARCHAR(50) NOT NULL,
     discussion TEXT,
     difficulty VARCHAR(50),
     thumbnail_url VARCHAR(255),
     audio_url VARCHAR(255)
     );

CREATE TABLE IF NOT EXISTS vocabularies (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     lesson_id BIGINT NOT NULL,
     chinese VARCHAR(50),
     pinyin VARCHAR(50),
     english VARCHAR(50),
     category VARCHAR(50),
     vocabulary_order INT
     );

CREATE TABLE IF NOT EXISTS dialogs (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     lesson_id BIGINT NOT NULL,
     chinese VARCHAR(50),
     pinyin VARCHAR(50),
     english VARCHAR(50),
     speaker VARCHAR(50),
     dialog_order INT
     );

CREATE TABLE IF NOT EXISTS users (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     last_name VARCHAR(100),
     first_name VARCHAR(100),
     email VARCHAR(100),
     password_hash VARCHAR(255),
     roles VARCHAR(255)
     );

CREATE TABLE IF NOT EXISTS user_likes (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     user_email VARCHAR(100),
     lesson_id BIGINT,
     gmt_timestamp BIGINT NOT NULL,
     CONSTRAINT user_likes_uq_1 UNIQUE (user_email, lesson_id)
     );

CREATE TABLE IF NOT EXISTS user_history (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     user_email VARCHAR(100),
     lesson_id BIGINT,
     gmt_timestamp BIGINT NOT NULL,
     CONSTRAINT user_history_uq_1 UNIQUE (user_email, lesson_id)
     );

